services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    networks:
      - internal
    environment:
    - POSTGRES_USER= ${POSTGRES_USER}
    - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
    - POSTGRES_DB= ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    container_name: POS
    build:
      context: .
      dockerfile: D:\GOLANG\BANKOMAT\Simple-ATM-on-REST\Dockerfile
    command: bash -c "go build -o main.go && . /main.go -b 0.0.0.0:8080 --timeout 120"
    expose:
      - 8080
    networks:
      - internal
    stdin_open: true
volumes:
  postgres_data:
  server:
networks:
  internal:
    driver: bridge